# Introdução à Numpy

<em> em construção

Um **módulo** é um arquivo contendo definições e comandos em Python, o qual pode ser importado para outros módulos

O nome de um módulo é o mesmo nome do arquivo .py contendo seu código

É possível que em algum momento você precise fazer o trabalho inverso, isto é, determinar o tipo de uma variável. A função type() permite fazer exatamente isto. Por exemplo,

Um módulo é compilado no momento de sua importação, gerando arquivos .pyc

Uma coleção de módulos dá origem a um **pacote**

O projeto SciPy é uma consiste de uma plataforma em Python para o desenvolvimento de softwares de matemática, ciência e engenharia.

- \textbf{NumPy}: tipos numéricos, arranjos e matrizes
- \textbf{SciPy}: coleção de algoritmos numéricos e toolboxes (signal processing, optimization, statistics and much more)
- \textbf{Matplotlib}: pacote para traçar gráficos 2D e 3D
- \textbf{pandas}: estruturas de dados de alto desempenho
- \textbf{SymPy}: álgebra computacional e computação simbólica
- \textbf{IPython}: ferramentas para auxiliar no processamento de dados
- \textbf{nose}: uma plataforma de testes

The numpy module2 is not a part of the standard Python release. As pointed out ear-
lier, it must be installed separately (the installation is very easy). The module intro-
duces array objects that are similar to lists, but can be manipulated by numerous
functions contained in the module. The size of an array is immutable, and no empty
elements are allowed.
The complete set of functions in numpy is far too long to be printed in its entirety.
The following list is limited to the most commonly used functions.




## Tipos de dados

Before we start, we must import the NumPy module. The preferred approach is to
preface the code with

In [26]:
import numpy as np

Once NumPy has been imported, we need to think about on-line documentation, for
this is a very large module. It is very straightforward to see how large NumPy is if
you are following my recommendation to use the IPython interpreter, which utilizes
tab completion, i.e., if we type part of a command and press the tab key, the range of
possible completions is shown, unless there is precisely one, in which case it will be
completed. Trying

### Tipos primitivos

|  tipo        |      intervalo    |
| ------------ | ----------------- |
| `bool`       | `True` ou `False` |
| `int32`      | -2147483648 a 2147483647|
| `complex128` |
- \textbf{int64}:	-9223372036854775808 a 9223372036854775807
- \textbf{uint32}:	0 a 4294967295
- \textbf{uint64}:	0 a 18446744073709551615
- \textbf{float32}:	bit p/ sinal, 8 bits p/ expoente, 23$^\text{*}$ bits p/ mantissa
- \textbf{float64}:	bit p/ sinal, 11 bits p/ expoente, 52$^\text{*}$ bits p/ mantissa
- \textbf{complex64}:	dois floats 32-bit
- \textbf{complex128}:	dois floats 64-bit

As características do sistema atual são exibidas conforme a seguir.

In [14]:
print(np.finfo(np.float))

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------



### Constantes

In [24]:
np.e, np.pi, np.inf, np.nan

(2.718281828459045, 3.141592653589793, inf, nan)

### Arranjos

ndarray is the main object of numpy, which is homogeneous (containing
only one data type for all its member elements). The elements are created
using the array() function of numpy. This functions needs a list as input.
Elements are indexed by a tuple of positive integers:

#### Construção de arranjos

Arranjos numéricos multi-dimensionais podem ser criados a partir de arranjos, listas e tuplas

In [25]:
a = np.array([[1,3.5],[-1,0],(1+1j,3.)])
a

array([[ 1. +0.j,  3.5+0.j],
       [-1. +0.j,  0. +0.j],
       [ 1. +1.j,  3. +0.j]])

Eles são muito mais do que simples arranjos.

In [19]:
a = np.arange(15).reshape(3, 5)
a,a.shape,a.ndim,a.dtype.name,a.itemsize,a.size,type(a)

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]), (3, 5), 2, 'int32', 4, 15, numpy.ndarray)

Há também funções de construção especiais

In [17]:
np.arange(10)
np.zeros((2, 3))
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

#### Acessando elementos de um arranjo

#### Operações com arranjos

As operações +, -, * são elemento a elemento

## Saiba mais