# Uma breve introdução à Numpy

<br>

Um **módulo** é um arquivo contendo definições e comandos em Python, o qual pode ser importado por outros módulos.
O nome de um módulo é o mesmo nome do arquivo `.py` contendo seu código.
Ele é compilado no momento de sua importação, gerando arquivos `.pyc`.
Uma coleção de módulos dá origem ao que chamamos de **pacote** ou **biblioteca**.

O projeto SciPy visa desenvolver uma plataforma para a implementação de softwares científicos e de engenharia.
A biblioteca **NumPy**, parte deste projeto, inclue tipos numéricos primitivos, arranjos numéricos semelhantes às listas e diversos algoritmos que manipulam estes dados. Ela será a biblioteca mais usada em nosso curso!

Antes de iniciarmos, iremos carregar nossa nova biblioteca:

In [55]:
import numpy as np

## Tipos de dados

### Tipos primitivos

`bool`
`int32`
`int64`
`uint32`
`uint64`
`float32`
`float64`
`complex64`
`complex128`

Podemos exibir as características de um tipo real específico usando a `numpy.finfo`:

In [42]:
print(np.finfo(np.float))

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------



## Constantes

In [56]:
np.e, np.pi, np.inf, np.nan

(2.718281828459045, 3.141592653589793, inf, nan)

## Arranjos

A `numpy.array` é o principal objeto da NumPy, um tipo de arranjo numérico homogêneo.
O tamanho de um arranjo é imutável e não pode ser criado com elementos vazios.

#### Construção de arranjos

In [57]:
a = np.array([[1,3.5],[-1,0],(1+1j,3.)])
a

array([[ 1. +0.j,  3.5+0.j],
       [-1. +0.j,  0. +0.j],
       [ 1. +1.j,  3. +0.j]])

Eles são muito mais do que simples arranjos.

In [45]:
a = np.arange(15).reshape(3, 5)
a,a.shape,a.ndim,a.dtype.name,a.itemsize,a.size,type(a)

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]), (3, 5), 2, 'int64', 8, 15, numpy.ndarray)

Há também funções de construção especiais:

In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

#### Acessando elementos de um arranjo

In [69]:
A = np.array([[3, 8, 2, 3],[8, 9, 7, 2],[6, 5, 5, 7],[6, 4, 5, 9]])
A[0,0],A[1,1]

(3, 9)

#### Operações com arranjos

As operações +, -, * são elemento a elemento. Por exemplo,

In [64]:
A = np.array([[3, 8, 2, 3],[8, 9, 7, 2],[6, 5, 5, 7],[6, 4, 5, 9]])
B = np.array([[7, 1, 3, 0],[6, 0, 2, 6],[2, 2, 1, 9],[8, 6, 7, 1]])
A*B

array([[21,  8,  6,  0],
       [48,  0, 14, 12],
       [12, 10,  5, 63],
       [48, 24, 35,  9]])

Para efetuarmos o produto matricial, conforme definido em álgebra, utilizamos a função `numpy.dot` (produto escalar).

In [65]:
np.dot(A,B)

array([[ 97,  25,  48,  69],
       [140,  34,  63, 119],
       [138,  58,  82,  82],
       [148,  70,  94,  78]])

## O auditor matricial

A Prefeitura de Frevolândia lançou edital para a contratação de novos *auditores matriciais*.
O requisito mínimo é ter cursado as disciplinas de Álgebra Linear e Programação Computacional em nível de graduação.
Compete ao auditor matricial verificar se o produto de duas matrizes quadradas de ordem $n$ está correto.
Ele atuará na fiscalização da mais nova empresa fornecedora de produtos matriciais, a Linear Consultoria, contratada para calcular o produto de matrizes fornecidas pela Secretaria da Previdência do município.
Dadas duas matrizes $\mathbf{A}$ e $\mathbf{B}$, fornecidas pela secretaria, e uma matriz $\mathbf{C}$ calculada pela Linear Consultoria, o auditor deverá verificar que $\mathbf{C} = \mathbf{A}\mathbf{B}$.

Entusiasmado com o concurso, Cícero decidiu se antecipar e já ir pensando como poderia realizar esses testes da forma mais rápida possível.

### Método determinístico

A primeira ideia que veio à mente de Cícero foi um método força bruta: calcular o produto $\mathbf{A}\mathbf{B}$ separadamente e verificar, elemento por elemento, se vale a igualdade $\mathbf{C} = \mathbf{A}\mathbf{B}$. Por conveniência, ele decidiu fazer seus testes usando Python e a biblioteca NumPy e acabou implementando a função abaixo.

In [48]:
# Complete esta função.
def forca_bruta(A,B,C):
    """Esta função verifica se vale a igualdade C = AB, usando força bruta.
    
    Argumentos:
        A,B,C (numpy.array): Matrizes quadradas com mesmas dimensões.

    Retorno:
        res (bool): True se verdadeiro, False caso contrário.
    """
    
    # Seu código deve iniciar aqui embaixo.
    
    return True # altere esta linha, caso necessário

*Verificação fictícia 1.*

In [62]:
%%time
A = np.array([[3, 8, 2, 3],[8, 9, 7, 2],[6, 5, 5, 7],[6, 4, 5, 9]])
B = np.array([[7, 1, 3, 0],[6, 0, 2, 6],[2, 2, 1, 9],[8, 6, 7, 1]])
C = np.array([[97, 25, 48, 69],[140, 34, 63, 119],[138, 58, 82, 82],[148, 70, 94, 78]])

forca_bruta(A,B,C)

CPU times: user 78 µs, sys: 0 ns, total: 78 µs
Wall time: 82.7 µs


True

*Verificação fictícia 2.*

In [50]:
%%time
C = np.array([[1, 1, 1, 4],[1, 0, 6, 9],[5, 5, 3, 1],[4, 0, 5, 3]])

forca_bruta(A,B,C)

CPU times: user 45 µs, sys: 10 µs, total: 55 µs
Wall time: 58.7 µs


True

### Método probabilístico

Refletindo sobre o problema, Cícero se fez a seguinte pergunta:

<blockquote>Dado um vetor $\mathbf{x}$ arbitrário, será que se tivermos $\mathbf{C} = \mathbf{A}\mathbf{B}$, também teremos $\mathbf{C}\mathbf{x} = \mathbf{A}\mathbf{B}\mathbf{x}$?
</blockquote>

#### **Exercício.**
Responda à pergunta de Cícero.

*Digite sua resposta nesta célula*

Seguindo nesta direção, ele elaborou o seguinte algoritmo:

1. Gere aleatoriamente um vetor $\mathbf{x}$ composto apenas por $0$'s e $1$'s
2. Calcule os produtos $\mathbf{C}\mathbf{x}$ e $\mathbf{A}(\mathbf{B}\mathbf{x})$
3. Se os resultados do item (2) forem os mesmos, a resposta será *sim*. Caso contrário, será *não*.

#### **Exercício.**
Você vê algum problema com o algoritmo de Cícero?

*Digite sua resposta nesta célula*

De repente, Cícero se enche de felicidade, pelo *insight* que acaba de ter. Ele decide então alterar seu algoritmo para:

1. Repita $50$ vezes o seguinte:  
  1.1 Gere aleatoriamente um vetor $\mathbf{x}$ composto apenas por $0$'s e $1$'s.  
  1.2 Calcule os produtos $\mathbf{C}\mathbf{x}$ e $\mathbf{A}(\mathbf{B}\mathbf{x})$.  
  1.3 Se os resultados do item (2) forem diferentes, a resposta será *não*.  
2. Se você chegou aqui, a resposta será *sim*.

#### **Exercício.**
Sua tarefa agora é implementar a última versão do algoritmo de Cícero.

*Digite sua resposta nesta célula*

In [51]:
# Complete esta função.
def probabilistico(A,B,C):
    """Esta função verifica se vale a igualdade C = AB, usando um algoritmo probabilístico.
    
    Argumentos:
        A,B,C (numpy.array): Matrizes quadradas com mesmas dimensões.

    Retorno:
        res (bool): True se verdadeiro, False caso contrário.
    """
    
    # Seu código deve iniciar aqui embaixo.
    
    return True # altere esta linha, caso necessário

*Verificação fictícia 1.*

In [52]:
%%time
C = np.array([[97, 25, 48, 69],[140, 34, 63, 119],[138, 58, 82, 82],[148, 70, 94, 78]])

probabilistico(A,B,C)

CPU times: user 44 µs, sys: 10 µs, total: 54 µs
Wall time: 57.9 µs


True

*Verificação fictícia 2.*

In [53]:
%%time
C = np.array([[1, 1, 1, 4],[1, 0, 6, 9],[5, 5, 3, 1],[4, 0, 5, 3]])

probabilistico(A,B,C)

CPU times: user 61 µs, sys: 0 ns, total: 61 µs
Wall time: 65.6 µs


True

Boa sorte, Cícero!

## Saiba mais

- Ao longo do curso, aprenderemos muito mais sobre a NumPy. Se você ficou curioso e quer saber mais sobre ela, sugiro que acesse: 

- O problema do "auditor matricial" foi inspirado na Miniatura 11 do livro do professor Jiří Matoušek,  **Thirty-three Miniatures: Mathematical and Algorithmic Appplications of Linear Algebra**, *Student Mathematical Library*, v. 53, AMS, 2010.


<br>
<p>&copy; 2019 Vicente Helano<br>
UFCA | Centro de Ciências e Tecnologia</p>